apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odoo

resources:
  - namespace.yaml
  - postgresql.yaml
  - odoo-deployment.yaml
  - odoo-service.yaml
  - odoo-ingress.yaml
  - odoo-unified-configmap.yaml
  - odoo-unified-secret.yaml
