apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo
  namespace: odoo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: ""  # Empty host for any domain/IP access
      http:
        paths:
          - backend:
              service:
                name: odoo
                port:
                  number: 8069
            path: /
            pathType: Prefix
          - backend:
              service:
                name: odoo
                port:
                  number: 8072
            path: /longpolling
            pathType: Prefix
